### PR TITLE
refactor!: Change the package name. Everyone knows it's java (or it doesn't matter)

### LINKED ISSUE #82: Change package name?
On the Sept 29 community call, an attendee suggested we remove "java" from the package names in the SDK (their argument was "java" is implied). I see their point, though I also don't think it's needed.

Basically: `dev.openfeature.javasdk` would become: `dev.openfeature.sdk`.

I'm just bringing this up because "now is the time" before we start marking things as stable. Mostly interested in @justinabrahms 's opinion on this one.

**UPDATE: We will likely do this at 1.0**

### PR DESCRIPTION
**Pull request by justinabrahms**
Fixes #82

### CODE REVIEW

**Comment by justinabrahms** [comment]
I believe this is blocked on a circular dependency w/ FlagD provider.

**Comment by toddbaert** [comment]
> I believe this is blocked on a circular dependency w/ FlagD provider.

Yep. The integration tests are already disabled for a similar reason. I've pushed an update that temporarily sidesteps this issue since the tests are disabled now anyways. I will restore it all once we've absorbed the changes in flagd.

**Review by toddbaert — DISMISSED** [review]

**Comment by toddbaert** [comment]
@justinabrahms looks like your 2nd commit is missing a signoff. I'm in favor of merging after that.

**Comment by toddbaert** [comment]
I re-applied my last commit on top. I'm assuming you removed it accidentally when you sign your old commits.

**Review by toddbaert — APPROVED** [review]

**Pull request merged**
