### PR TITLE
chore: release 1.0.0

### PR DESCRIPTION
**Pull request by toddbaert**
Release-As: 1.0.0

### CODE REVIEW

**Review by beeme1mr — CHANGES_REQUESTED** [review]
Remove the work in progress badge from the readme.

**Comment by toddbaert** [comment]
> Remove the work in progress badge from the readme.

ok

**Review by beeme1mr — APPROVED** [review]

**Comment by beeme1mr** [comment]
Hey @justinabrahms, do you have any concerns about this? I would like to get it in as soon as possible.

**Comment by toddbaert** [comment]
Merging per slack message: https://cloud-native.slack.com/archives/C0344AANLA1/p1666713678475379

**Review by beeme1mr — APPROVED** [review]

**Pull request closed without merging**
